# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP


#kind: Cluster
#apiVersion: kind.x-k8s.io/v1alpha4
#nodes:
#  - role: control-plane
#    extraPortMappings:
#      - containerPort: 80
#        hostPort: 80
#        listenAddress: "192.168.0.45" # Your machine’s LAN IP
#      - containerPort: 443
#        hostPort: 443
#        listenAddress: "192.168.0.45" # For HTTPS if needed
#networking:
#  apiServerAddress: "192.168.0.45"
#  apiServerPort: 6443


#  systemd-run --scope --user -p "Delegate=yes" kind create cluster --name cluster-spring-microservices --image kindest/node:v1.29.2 --config kind-config.yaml
