services:
  accounts:
    image: eroskoller/accounts:s04
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - eazybank
  cards:
    image: eroskoller/cards:s04
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      - accounts
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - eazybank
  loans:
    image: eroskoller/loans:s04
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      - cards
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - eazybank

networks:
  eazybank:
    driver: bridge