server:
  port: 9000

spring:
  config:
    import:
      - application_qa.yml
      - application_prod.yml
  profiles:
    active:
      - "${SPRING_PROFILES_ACTIVE:qa}"
  application.name: cads
  #  devtools:
  #    restart:
  #      trigger-file: .reloadtrigger
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


build:
  version: "3.0"

cards:
  message: "Welcome to Cards Developer Mode Microservice"
  contactDetails:
    name: "Eros Koller"
    email: "eroskoller@gmail.com"
  onCallSupport:
    - (+55) 11 99999-9999
    - (+55) 11 88888-8888


