build:
  version: "1.0"

cards:
  message: "Welcome to Prod Cards Microservice"
  contactDetails:
    name: "Eros Koller"
    email: "eroskoller@gmail.com"
  onCallSupport:
    - (+55) 11 99999-9999
    - (+55) 11 88888-8888