server:
  port: 9000

spring:
  application:
    name: cards
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:qa}"
  config:
    import: "${SPRING_CLOUD_CONFIG_URI:optional:configserver:http://localhost:8071/}"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  #  devtools:
  #    restart:
  #      trigger-file: .reloadtrigger
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: "${POSTGRES_URI:jdbc:postgresql://localhost:5432/eazybank}"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: cards
    description: Cards Microservice
    version: 1.0.0
    build: 1.0.0
    environment: default

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG


