build:
  version: "3.0"

loans:
  message: "Welcome to Developer Loans Microservice"
  contactDetails:
    name: "Eros Koller"
    email: "eroskoller@gmail.com"
  onCallSupport:
    - (+55) 11 99999-9999
    - (+55) 11 88888-8888


