server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/}"
  devtools:
    restart:
      enabled: false
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  #      routes:
  #        - id: per_route_timeouts
  #          uri: https://example.org
  #          predicates:
  #            - name: Path
  #              args:
  #                pattern: /delay/{timeout}
  #          metadata:
  #            response-timeout: 200
  #            connect-timeout: 200

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      #      enabled: true
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: Gateway Server Microservice
    version: 1.0.0
    build: 1.0.0
    environment: default

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG